export { default as LandingPage } from "./landingPage";
export { default as AboutUs } from "./aboutUs";
export { default as Login } from "./login";
export { default as Signup } from "./signup";
export { default as ForgotPassword } from "./forgotPassword";
export { default as Success } from "./success";
export { default as ChangePassword } from "./changePassword";
export { default as EmailVerified } from "./emailVerified";
export { default as Inspiration } from "./inspiration";
